name: Build Web2Apk
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu‑latest
    steps:
      - uses: actions/checkout@v4
      - name: build apk
        uses: lw112190/web2android‑action@v0.2.7
        with:
          source_dir: ./
          app_name: "点名助手"
          package_name: "com.dianming.leo"
          version_name: "1.0.0"
          version_code: 1
          internet: false
      - name: upload artifact
        uses: actions/upload‑artifact@v4
        with:
          path: "*.apk"
